-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsrf9pxPwj8vPefb4
1xTyt0WWVhaAIBzjQq0v+CNt+M2gCgYIKoZIzj0DAQehRANCAASJjq+FujFs1auN
HSziwzt5S64GTdnmmfHCi79xMENYnDtPY6Hm7ry4Yfd+5FTfe9OkMmwLAvCtfkI6
xSIGWFPE
-----END PRIVATE KEY-----